# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bevYTvWpT8V-ckDRianLOkQMyPR-dpvN
"""

from fastapi import FastAPI
from pydantic import BaseModel
import numpy as np
import joblib

# =========================
# Загрузка модели
# =========================

model = joblib.load("model.pkl")

# =========================
# Создание API
# =========================

app = FastAPI(
    title="Diabetes Prediction API",
    description="API для предсказания диабета",
    version="1.0"
)

# =========================
# Структура входных данных
# =========================

class DiabetesInput(BaseModel):
    Pregnancies: float
    Glucose: float
    BloodPressure: float
    SkinThickness: float
    Insulin: float
    BMI: float
    DiabetesPedigreeFunction: float
    Age: float

# =========================
# Главная страница
# =========================

@app.get("/")
def home():
    return {
        "message": "Diabetes Prediction API работает"
    }

# =========================
# Предсказание
# =========================

@app.post("/predict")
def predict(data: DiabetesInput):

    features = np.array([[
        data.Pregnancies,
        data.Glucose,
        data.BloodPressure,
        data.SkinThickness,
        data.Insulin,
        data.BMI,
        data.DiabetesPedigreeFunction,
        data.Age
    ]])

    prediction = model.predict(features)[0]

    probability = model.predict_proba(features)[0][1]

    result = "Diabetes" if prediction == 1 else "No Diabetes"

    return {
        "prediction": int(prediction),
        "result": result,
        "probability": round(float(probability), 4)
    }