# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bevYTvWpT8V-ckDRianLOkQMyPR-dpvN
"""

from fastapi import FastAPI
from pydantic import BaseModel
import numpy as np
import joblib

model = joblib.load("model.pkl")

app = FastAPI(
    title="Прогнозирование диабаета",
    version="1.0"
)


class DiabetesInput(BaseModel):
    Pregnancies: float
    Glucose: float
    BloodPressure: float
    SkinThickness: float
    Insulin: float
    BMI: float
    DiabetesPedigreeFunction: float
    Age: float

@app.get("/")
def home():
    return {
        "message": "API работает"
    }

@app.post("/predict")
def predict(data: DiabetesInput):

    features = np.array([[
        data.Pregnancies,
        data.Glucose,
        data.BloodPressure,
        data.SkinThickness,
        data.Insulin,
        data.BMI,
        data.DiabetesPedigreeFunction,
        data.Age
    ]])

    prediction = model.predict(features)[0]

    probability = model.predict_proba(features)[0][1]

    result = "Диабет" if prediction == 1 else "Нет диабета"

    return {
    "Результат": int(prediction),
    "Диагноз": result,
    "Вероятность": float(probability)
    }
