# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bevYTvWpT8V-ckDRianLOkQMyPR-dpvN
"""

from fastapi import FastAPI
from pydantic import BaseModel
import numpy as np
import joblib

# загрузка модели
model = joblib.load("model.pkl")

# создание FastAPI
app = FastAPI(
    title="Diabetes Prediction API",
    description="API для предсказания диабета",
    version="1.0"
)

# структура входных данных
class DiabetesInput(BaseModel):
    Pregnancies: float
    Glucose: float
    BloodPressure: float
    SkinThickness: float
    Insulin: float
    BMI: float
    DiabetesPedigreeFunction: float
    Age: float

# главная страница
@app.get("/")
def home():
    return {
        "message": "API работает"
    }

# predict
@app.post("/predict")
def predict(data: DiabetesInput):

    features = np.array([[
        data.Pregnancies,
        data.Glucose,
        data.BloodPressure,
        data.SkinThickness,
        data.Insulin,
        data.BMI,
        data.DiabetesPedigreeFunction,
        data.Age
    ]])

    prediction = model.predict(features)[0]

    probability = model.predict_proba(features)[0][1]

    return {
        "prediction": int(prediction),
        "probability": float(probability)
    }
