# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bevYTvWpT8V-ckDRianLOkQMyPR-dpvN
"""

import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from xgboost import XGBClassifier

# =========================
# Загрузка данных
# =========================

df = pd.read_csv("diabetes.csv")

# =========================
# Признаки и target
# =========================

X = df.drop("Outcome", axis=1)
y = df["Outcome"]

# =========================
# Деление выборки
# =========================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.33,
    random_state=42,
    stratify=y
)

# =========================
# Обучение модели
# =========================

model = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

model.fit(X_train, y_train)

# =========================
# Проверка модели
# =========================

predictions = model.predict(X_test)

print(classification_report(y_test, predictions))

# =========================
# Сохранение модели
# =========================

joblib.dump(model, "model.pkl")

print("Модель успешно сохранена!")